from pathlib import Path
from typing import Optional

from .utils import info, warn
from .constants import DEFAULT_NGINX_CONF

GENERATED_MARKER = "# Generated by orchestration.nginx (constants fallback)"


def _looks_sane(text: str) -> bool:
    """
    Lightweight sanity check for an nginx default.conf. We don't parse;
    we just ensure a few must-have bits appear. We *warn only* on failure.
    """
    return all(needle in text for needle in ("server {", "location /", "fastcgi_pass php:9000"))


def ensure_nginx_conf() -> Path:
    """
    Ensure nginx/conf.d/default.conf exists with a Magento-friendly config.

    Preference order:
      1) ./templates/nginx/default.conf (if present)
      2) constants.DEFAULT_NGINX_CONF (with a one-line generated marker)

    Never overwrite existing local configs. If an existing file looks off, warn only.
    """
    conf_dir = Path("./nginx/conf.d")
    conf_file = conf_dir / "default.conf"
    conf_dir.mkdir(parents=True, exist_ok=True)

    if conf_file.exists():
        try:
            text = conf_file.read_text(encoding="utf-8")
            if not _looks_sane(text):
                warn(f"{conf_file} failed sanity checks; leaving as-is (warn-only).")
        except Exception as e:
            warn(f"Could not read {conf_file}; leaving as-is. ({e})")
        return conf_file

    # Prefer template if present
    template_path = Path("./templates/nginx/default.conf")
    if template_path.exists():
        conf_file.write_text(template_path.read_text(encoding="utf-8"), encoding="utf-8")
        info(f"Created Nginx config from template at {conf_file}")
        return conf_file

    # Fallback to constants with a one-line generated marker
    conf_file.write_text(f"{GENERATED_MARKER}\n{DEFAULT_NGINX_CONF}", encoding="utf-8")
    info(f"Created default Nginx config at {conf_file} (constants fallback)")
    return conf_file


def ensure_src_stub() -> None:
    """
    Create ./src/index.php stub if ./src is empty; validates PHP↔Nginx wiring.
    """
    src = Path("./src")
    src.mkdir(parents=True, exist_ok=True)
    if any(src.iterdir()):
        return
    # Write literal '<?php phpinfo();'
    (src / "index.php").write_text("<?php phpinfo();", encoding="utf-8")
    info("Created ./src/index.php stub (directory was empty)")
